spring.application.name=devTools
server.port = 9000

# Connection Details
spring.datasource.url=jdbc:mysql://localhost:3306/prod-ready-feature?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=M@nthan2104

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


employee.base.url=http://localhost:8080



##it configures devtools restart ( whether to rebuild the application or not)
#spring.devtools.restart.enabled = true
#
##any classpath you don't want to rebuild while application being to restart.
#spring.devtools.restart.exclude = com/week4/devTools/dto

#it sets the time for restarting devtools in every (20) millisecond
#spring.devtools.restart.pollInterval = 20


#spring.devtools.restart.quietPeriod = 10