spring.application.name=mvc-restfulAPIs
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:M:/DSA/Databases/Week 2/Homework
spring.datasource.username=Manthan
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update